In [1]:
import numpy as np
import pandas as pd
%run LAZY_FCA.ipynb

In [2]:
fruits_f = np.array([
        'white',
        'yellow',
        'green',
        'blue',
        'fruit',
        'not_fruit',
        'smooth',
        'not_smooth',
        'round',
        'not_round'
    ])

fruits_d = np.array([
    #fruit
    [2, 1, 2, 2, 2, 1, 1, 2, 1, 2],
    [2, 1, 2, 2, 2, 1, 2, 1, 1, 2],
    [2, 2, 1, 2, 2, 1, 2, 1, 2, 1],
    [2, 2, 2, 1, 2, 1, 1, 2, 2, 1],
    #not fruit
    [2, 2, 1, 2, 1, 2, 1, 2, 2, 1],
    [1, 2, 2, 2, 1, 2, 1, 2, 2, 1],
    [2, 1, 2, 2, 1, 2, 2, 1, 1, 2],
])

df = pd.DataFrame(fruits_d, columns=fruits_f)
df

white  yellow  green  blue  fruit  not_fruit  smooth  not_smooth  round  \
0      2       1      2     2      2          1       1           2      1   
1      2       1      2     2      2          1       2           1      1   
2      2       2      1     2      2          1       2           1      2   
3      2       2      2     1      2          1       1           2      2   
4      2       2      1     2      1          2       1           2      2   
5      1       2      2     2      1          2       1           2      2   
6      2       1      2     2      1          2       2           1      1   

   not_round  
0          2  
1          2  
2          1  
3          1  
4          1  
5          1  
6          2

In [3]:
mango = np.array([
    [2, 2, 1, 2, 2, 1, 1, 2, 2, 1]
])
mango

array([[2, 2, 1, 2, 2, 1, 1, 2, 2, 1]])

In [4]:
positive = fruits_d[:4]
negative = fruits_d[4:]

### FCA EXAMPLE

In [5]:
fca = FCA(1)
fca.fca(mango, positive, negative, 1, 1)

Postive
The intesection of test and train data is :
[2 2 1 2 2 1 1 2 2 1] [2 1 2 2 2 1 1 2 1 2] [0, 0, 0, 0, 0, 1, 1, 0, 0, 0]
[2 2 1 2 2 1 1 2 2 1] [2 1 2 2 2 1 2 1 1 2] [0, 0, 0, 0, 0, 1, 0, 0, 0, 0]
[2 2 1 2 2 1 1 2 2 1] [2 2 1 2 2 1 2 1 2 1] [0, 0, 1, 0, 0, 1, 0, 0, 0, 1]
[2 2 1 2 2 1 1 2 2 1] [2 2 2 1 2 1 1 2 2 1] [0, 0, 0, 0, 0, 1, 1, 0, 0, 1]

 The result of intersection result of positive element and positive train is :

 [[['*' '*' '*' '*' '*' '1' '1' '*' '*' '*']
  ['*' '*' '*' '*' '*' '1' '0' '*' '*' '*']
  ['*' '*' '*' '*' '*' '1' '0' '*' '*' '*']
  ['*' '*' '*' '*' '*' '1' '1' '*' '*' '*']]

 [['*' '*' '*' '*' '*' '1' '*' '*' '*' '*']
  ['*' '*' '*' '*' '*' '1' '*' '*' '*' '*']
  ['*' '*' '*' '*' '*' '1' '*' '*' '*' '*']
  ['*' '*' '*' '*' '*' '1' '*' '*' '*' '*']]

 [['*' '*' '0' '*' '*' '1' '*' '*' '*' '0']
  ['*' '*' '0' '*' '*' '1' '*' '*' '*' '0']
  ['*' '*' '1' '*' '*' '1' '*' '*' '*' '1']
  ['*' '*' '0' '*' '*' '1' '*' '*' '*' '1']]

 [['*' '*' '*' '*' '*' '1' '1' '

(71.42857142857143, 28.57142857142857)